<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class SyncSequences extends Command
{
    protected $signature = 'db:sync-sequences {--table=* : Limitar a tablas específicas} {--dry-run : Mostrar acciones sin aplicarlas}';
    protected $description = 'Sincroniza secuencias/identity de columnas id con el MAX(id)+1 en PostgreSQL';

    public function handle(): int
    {
        $driver = DB::connection()->getDriverName();
        if ($driver !== 'pgsql') {
            $this->error("Este comando solo soporta PostgreSQL. Driver actual: {$driver}");
            return self::FAILURE;
        }

        $limitTables = collect((array) $this->option('table'))
            ->filter(fn($t) => is_string($t) && $t !== '')
            ->values();

        $rows = DB::select(<<<SQL
            SELECT
                c.table_schema,
                c.table_name,
                c.column_name,
                c.column_default,
                c.is_identity,
                c.data_type
            FROM information_schema.columns c
            JOIN information_schema.tables t
              ON t.table_schema = c.table_schema AND t.table_name = c.table_name
            WHERE c.column_name = 'id'
              AND t.table_type = 'BASE TABLE'
              AND c.table_schema = 'public'
            ORDER BY c.table_name
        SQL);

        $tables = collect($rows)
            ->map(fn($r) => [
                'schema' => $r->table_schema,
                'table' => $r->table_name,
                'default' => $r->column_default,
                'is_identity' => strtoupper((string) $r->is_identity) === 'YES',
                'data_type' => strtolower((string) $r->data_type),
            ])
            ->when($limitTables->isNotEmpty(), fn($col) => $col->whereIn('table', $limitTables->all()))
            ->values();

        if ($tables->isEmpty()) {
            $this->info('No se encontraron tablas con columna id.');
            return self::SUCCESS;
        }

        $dry = (bool) $this->option('dry-run');
        $this->info(($dry ? '[DRY-RUN] ' : '') . 'Tablas a procesar: ' . $tables->pluck('table')->implode(', '));

        foreach ($tables as $t) {
            $fq = '"' . $t['schema'] . '"."' . $t['table'] . '"';

            // Saltar IDs no numéricos (UUID, texto, etc.)
            $numericTypes = ['smallint','integer','bigint','numeric','decimal'];
            if (!in_array($t['data_type'], $numericTypes, true)) {
                $this->line("{$t['table']}: tipo id '{$t['data_type']}' no numérico; se omite");
                continue;
            }

            $nextRow = DB::selectOne('SELECT COALESCE(MAX(id),0)+1 AS next FROM ' . '"' . $t['table'] . '"');
            $next = (int) ($nextRow->next ?? 1);

            $hasNextval = is_string($t['default'] ?? null) && str_contains($t['default'], 'nextval(');
            $isIdentity = (bool) $t['is_identity'];

            if ($isIdentity) {
                $this->line("{$t['table']}: identity detectado; RESTART WITH {$next}");
                if (!$dry) {
                    DB::statement("ALTER TABLE {$fq} ALTER COLUMN id RESTART WITH {$next}");
                }
                continue;
            }

            if ($hasNextval) {
                $this->line("{$t['table']}: secuencia (nextval) detectada; setval a {$next}");
                if (!$dry) {
                    DB::statement("SELECT setval(pg_get_serial_sequence('" . $t['table'] . "','id'), {$next}, false)");
                }
                continue;
            }

            // Sin default ni identity: agregar identity y reiniciar
            $this->warn("{$t['table']}: id sin default/identity; agregando GENERATED BY DEFAULT AS IDENTITY y RESTART WITH {$next}");
            if (!$dry) {
                try {
                    DB::statement("ALTER TABLE {$fq} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
                } catch (\Throwable $e) {
                    $this->error("  Error al agregar identity en {$t['table']}: " . $e->getMessage());
                }
                try {
                    DB::statement("ALTER TABLE {$fq} ALTER COLUMN id RESTART WITH {$next}");
                } catch (\Throwable $e) {
                    $this->error("  Error al reiniciar identity en {$t['table']}: " . $e->getMessage());
                }
            }
        }

        $this->info('Proceso completado.');
        return self::SUCCESS;
    }
}

