<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Equipo;

class EquipoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $equipos = [
            [
                'codigo' => 'PC001',
                'nombre' => 'Computadora de Escritorio',
                'marca' => 'Dell',
                'modelo' => 'OptiPlex 3080',
                'numero_serie' => 'DELL123456',
                'descripcion' => 'Computadora de escritorio para punto de venta',
                'especificaciones' => ['Procesador' => 'Intel Core i5', 'RAM' => '8GB', 'Disco' => '256GB SSD'],
                'precio_renta_mensual' => 1500.00,
                'precio_compra' => 12000.00,
                'fecha_adquisicion' => '2023-01-15',
                'estado' => 'disponible',
                'condicion' => 'excelente',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Equipo nuevo, listo para instalación',
                'accesorios' => ['Teclado', 'Mouse', 'Monitor 22"'],
                'fecha_garantia' => '2026-01-15',
                'proveedor' => 'Dell México',
            ],
            [
                'codigo' => 'LEC001',
                'nombre' => 'Lector de Código de Barras',
                'marca' => 'Honeywell',
                'modelo' => 'Voyager 1202g',
                'numero_serie' => 'HON789012',
                'descripcion' => 'Lector láser inalámbrico para códigos 1D y 2D',
                'especificaciones' => ['Tipo' => 'Láser', 'Alcance' => 'Hasta 10m', 'Conexión' => 'Bluetooth'],
                'precio_renta_mensual' => 300.00,
                'precio_compra' => 2500.00,
                'fecha_adquisicion' => '2023-02-10',
                'estado' => 'disponible',
                'condicion' => 'nuevo',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Incluye base de carga',
                'accesorios' => ['Base de carga', 'Cable USB'],
                'fecha_garantia' => '2025-02-10',
                'proveedor' => 'Honeywell',
            ],
            [
                'codigo' => 'BAS001',
                'nombre' => 'Báscula Digital',
                'marca' => 'Ohaus',
                'modelo' => 'Valor 3000',
                'numero_serie' => 'OHA345678',
                'descripcion' => 'Báscula digital de precisión para productos',
                'especificaciones' => ['Capacidad' => '30kg', 'Precisión' => '0.01kg', 'Pantalla' => 'LCD'],
                'precio_renta_mensual' => 400.00,
                'precio_compra' => 3500.00,
                'fecha_adquisicion' => '2023-03-05',
                'estado' => 'disponible',
                'condicion' => 'bueno',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Calibrada recientemente',
                'accesorios' => ['Adaptador de corriente'],
                'fecha_garantia' => '2025-03-05',
                'proveedor' => 'Ohaus México',
            ],
            [
                'codigo' => 'IMP001',
                'nombre' => 'Impresora de Tickets',
                'marca' => 'Epson',
                'modelo' => 'TM-T88VI',
                'numero_serie' => 'EPS901234',
                'descripcion' => 'Impresora térmica para tickets de venta',
                'especificaciones' => ['Velocidad' => '300mm/s', 'Ancho' => '80mm', 'Conexión' => 'USB + Ethernet'],
                'precio_renta_mensual' => 500.00,
                'precio_compra' => 4500.00,
                'fecha_adquisicion' => '2023-04-20',
                'estado' => 'disponible',
                'condicion' => 'excelente',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Compatible con sistema POS',
                'accesorios' => ['Cable USB', 'Papel térmico'],
                'fecha_garantia' => '2026-04-20',
                'proveedor' => 'Epson México',
            ],
            [
                'codigo' => 'MON001',
                'nombre' => 'Monitor LCD 22"',
                'marca' => 'Samsung',
                'modelo' => 'S22F350',
                'numero_serie' => 'SAM567890',
                'descripcion' => 'Monitor LCD de 22 pulgadas para punto de venta',
                'especificaciones' => ['Tamaño' => '22"', 'Resolución' => '1920x1080', 'Conexión' => 'HDMI + VGA'],
                'precio_renta_mensual' => 250.00,
                'precio_compra' => 2000.00,
                'fecha_adquisicion' => '2023-05-12',
                'estado' => 'disponible',
                'condicion' => 'nuevo',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Panel IPS, ángulo de visión amplio',
                'accesorios' => ['Cable HDMI', 'Cable VGA'],
                'fecha_garantia' => '2025-05-12',
                'proveedor' => 'Samsung Electronics',
            ],
            [
                'codigo' => 'TECL001',
                'nombre' => 'Teclado USB',
                'marca' => 'Logitech',
                'modelo' => 'K380',
                'numero_serie' => 'LOG112233',
                'descripcion' => 'Teclado inalámbrico multi-dispositivo',
                'especificaciones' => ['Conexión' => 'Bluetooth', 'Batería' => 'Hasta 2 años', 'Compatibilidad' => 'Multi-plataforma'],
                'precio_renta_mensual' => 100.00,
                'precio_compra' => 800.00,
                'fecha_adquisicion' => '2023-06-08',
                'estado' => 'disponible',
                'condicion' => 'bueno',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Conectable hasta 3 dispositivos',
                'accesorios' => ['Manual de usuario'],
                'fecha_garantia' => '2025-06-08',
                'proveedor' => 'Logitech',
            ],
            [
                'codigo' => 'MOUSE001',
                'nombre' => 'Mouse Óptico USB',
                'marca' => 'Logitech',
                'modelo' => 'M185',
                'numero_serie' => 'LOG445566',
                'descripcion' => 'Mouse óptico inalámbrico',
                'especificaciones' => ['DPI' => '1000', 'Batería' => 'Hasta 1 año', 'Botones' => '2 + scroll'],
                'precio_renta_mensual' => 80.00,
                'precio_compra' => 250.00,
                'fecha_adquisicion' => '2023-07-15',
                'estado' => 'disponible',
                'condicion' => 'nuevo',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Mini receptor USB incluido',
                'accesorios' => ['Receptor USB'],
                'fecha_garantia' => '2025-07-15',
                'proveedor' => 'Logitech',
            ],
            [
                'codigo' => 'ROUTER001',
                'nombre' => 'Router WiFi',
                'marca' => 'TP-Link',
                'modelo' => 'Archer C6',
                'numero_serie' => 'TPL778899',
                'descripcion' => 'Router inalámbrico AC1200 para conexión a internet',
                'especificaciones' => ['Velocidad' => '1200Mbps', 'Bandas' => '2.4GHz + 5GHz', 'Puertos' => '4 LAN + 1 WAN'],
                'precio_renta_mensual' => 200.00,
                'precio_compra' => 1500.00,
                'fecha_adquisicion' => '2023-08-22',
                'estado' => 'disponible',
                'condicion' => 'excelente',
                'ubicacion_fisica' => 'Almacén Principal',
                'notas' => 'Configurado para redes comerciales',
                'accesorios' => ['Adaptador de corriente', 'Cable Ethernet'],
                'fecha_garantia' => '2025-08-22',
                'proveedor' => 'TP-Link México',
            ],
        ];

        foreach ($equipos as $equipo) {
            Equipo::create($equipo);
        }
    }
}
