<?php

namespace Database\Seeders;

use App\Models\Herramienta;
use App\Models\Tecnico;
use App\Models\CategoriaHerramienta;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HerramientaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener técnicos y categorías existentes
        $tecnicos = Tecnico::all();
        $categorias = CategoriaHerramienta::all();

        // Mapear categorías por slug para fácil acceso
        $categoriaMap = $categorias->pluck('id', 'slug')->toArray();

        $herramientas = [
            // HERRAMIENTAS ELÉCTRICAS
            [
                'nombre' => 'Taladro inalámbrico Bosch GSB 18V-60',
                'numero_serie' => 'TLR-BSH-001-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 36,
                'costo_reemplazo' => 2500.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 180,
                'descripcion' => 'Taladro inalámbrico profesional de 18V con batería de litio. Ideal para perforaciones en madera, metal y concreto.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Sierra circular Makita 7-1/4"',
                'numero_serie' => 'SCR-MKT-002-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 48,
                'costo_reemplazo' => 3200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 120,
                'descripcion' => 'Sierra circular de 7-1/4" con motor de 15 AMP. Perfecta para cortes precisos en madera y materiales compuestos.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Amoladora angular Makita GA4530',
                'numero_serie' => 'AML-MKT-003-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 42,
                'costo_reemplazo' => 1800.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 90,
                'descripcion' => 'Amoladora angular de 4-1/2" con motor de 6 AMP. Excelente para corte y desbaste de metales.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Destornillador eléctrico Bosch IXO V',
                'numero_serie' => 'DST-BSH-004-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 60,
                'costo_reemplazo' => 800.00,
                'requiere_mantenimiento' => false,
                'dias_para_mantenimiento' => null,
                'descripcion' => 'Destornillador inalámbrico compacto con batería integrada. Ideal para trabajos de precisión.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Sierra de calar Dewalt DCS331',
                'numero_serie' => 'SRC-DWT-005-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 40,
                'costo_reemplazo' => 2200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 150,
                'descripcion' => 'Sierra de calar con sistema de cambio rápido de hojas. Versátil para cortes curvos y rectos.',
                'foto' => null,
                'tecnico_id' => null,
            ],

            // HERRAMIENTAS MANUALES
            [
                'nombre' => 'Kit de herramientas Stanley 65 piezas',
                'numero_serie' => 'KIT-STN-006-2024',
                'categoria_id' => $categoriaMap['manual'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 120,
                'costo_reemplazo' => 1500.00,
                'requiere_mantenimiento' => false,
                'dias_para_mantenimiento' => null,
                'descripcion' => 'Kit completo de herramientas manuales con caja organizadora. Incluye llaves, destornilladores y pinzas.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Llave de tubo ajustable Ridgid 12"',
                'numero_serie' => 'LLV-RDG-007-2024',
                'categoria_id' => $categoriaMap['manual'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 180,
                'costo_reemplazo' => 450.00,
                'requiere_mantenimiento' => false,
                'dias_para_mantenimiento' => null,
                'descripcion' => 'Llave de tubo ajustable profesional de 12". Ideal para trabajos de plomería e instalaciones.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Alicates de corte Milwaukee',
                'numero_serie' => 'ALC-MKE-008-2024',
                'categoria_id' => $categoriaMap['manual'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 96,
                'costo_reemplazo' => 280.00,
                'requiere_mantenimiento' => false,
                'dias_para_mantenimiento' => null,
                'descripcion' => 'Alicates de corte profesional con mangos ergonómicos. Excelente para trabajos eléctricos.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],

            // HERRAMIENTAS DE MEDICIÓN
            [
                'nombre' => 'Multímetro digital Fluke 87V',
                'numero_serie' => 'MLT-FLK-009-2024',
                'categoria_id' => $categoriaMap['medicion'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 84,
                'costo_reemplazo' => 1200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 365,
                'descripcion' => 'Multímetro digital profesional con pantalla LCD. Medición precisa de voltaje, corriente y resistencia.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Nivel láser Bosch GLL 30',
                'numero_serie' => 'NVL-BSH-010-2024',
                'categoria_id' => $categoriaMap['medicion'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 72,
                'costo_reemplazo' => 1800.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 180,
                'descripcion' => 'Nivel láser de línea con proyección horizontal y vertical. Precisión de 1/8" a 30 pies.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Medidor de distancia láser Leica Disto D2',
                'numero_serie' => 'MED-LCA-011-2024',
                'categoria_id' => $categoriaMap['medicion'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 60,
                'costo_reemplazo' => 2500.00,
                'requiere_mantenimiento' => false,
                'dias_para_mantenimiento' => null,
                'descripcion' => 'Medidor láser de distancia con precisión de 1.5mm. Alcance hasta 100 metros.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],

            // HERRAMIENTAS DE SEGURIDAD
            [
                'nombre' => 'Arnés de seguridad FallTech',
                'numero_serie' => 'ARN-FTK-012-2024',
                'categoria_id' => $categoriaMap['seguridad'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 24,
                'costo_reemplazo' => 800.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 90,
                'descripcion' => 'Arnés completo de seguridad con absorbedor de energía. Certificado para trabajos en alturas.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Gafas de seguridad UVEX',
                'numero_serie' => 'GAF-UVX-013-2024',
                'categoria_id' => $categoriaMap['seguridad'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 12,
                'costo_reemplazo' => 150.00,
                'requiere_mantenimiento' => false,
                'dias_para_mantenimiento' => null,
                'descripcion' => 'Gafas de seguridad con protección UV y antiempañante. Ideales para trabajos con soldadura.',
                'foto' => null,
                'tecnico_id' => null,
            ],

            // HERRAMIENTAS DE LIMPIEZA
            [
                'nombre' => 'Aspiradora industrial Shop-Vac',
                'numero_serie' => 'ASP-SHV-014-2024',
                'categoria_id' => $categoriaMap['limpieza'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 36,
                'costo_reemplazo' => 950.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 180,
                'descripcion' => 'Aspiradora industrial de 5 HP con filtro HEPA. Perfecta para limpieza de áreas de trabajo.',
                'foto' => null,
                'tecnico_id' => null,
            ],

            // HERRAMIENTAS DE CONSTRUCCIÓN
            [
                'nombre' => 'Martillo neumático Hilti TE 30',
                'numero_serie' => 'MRT-HLT-015-2024',
                'categoria_id' => $categoriaMap['construccion'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 30,
                'costo_reemplazo' => 4500.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 60,
                'descripcion' => 'Martillo neumático profesional para demolición. Potencia de 1.7 joules por golpe.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Elevador hidráulico Genie GS-1930',
                'numero_serie' => 'ELV-GNE-016-2024',
                'categoria_id' => $categoriaMap['construccion'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 72,
                'costo_reemplazo' => 15000.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 90,
                'descripcion' => 'Elevador hidráulico de tijera con capacidad de 19 pies. Plataforma para 2 personas.',
                'foto' => null,
                'tecnico_id' => null,
            ],

            // HERRAMIENTAS ELECTRÓNICAS
            [
                'nombre' => 'Soldador eléctrico Lincoln Precision TIG 375',
                'numero_serie' => 'SLD-LNC-017-2024',
                'categoria_id' => $categoriaMap['electronica'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 48,
                'costo_reemplazo' => 8500.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 120,
                'descripcion' => 'Soldador TIG profesional con control digital. Ideal para trabajos de precisión en aluminio.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Cortadora de plasma Miller Spectrum 375',
                'numero_serie' => 'CRT-MLR-018-2024',
                'categoria_id' => $categoriaMap['electronica'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 42,
                'costo_reemplazo' => 7200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 90,
                'descripcion' => 'Cortadora de plasma profesional con capacidad de corte hasta 3/8" de acero.',
                'foto' => null,
                'tecnico_id' => null,
            ],

            // HERRAMIENTAS VARIAS (OTRA)
            [
                'nombre' => 'Generador portátil Honda EU2200i',
                'numero_serie' => 'GEN-HND-019-2024',
                'categoria_id' => $categoriaMap['otra'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 60,
                'costo_reemplazo' => 3200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 180,
                'descripcion' => 'Generador inverter silencioso de 2200W. Ideal para herramientas eléctricas en campo.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Compresor de aire Ingersoll Rand SS5',
                'numero_serie' => 'CMP-IRD-020-2024',
                'categoria_id' => $categoriaMap['otra'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 84,
                'costo_reemplazo' => 5800.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 120,
                'descripcion' => 'Compresor de aire de 5 HP con tanque de 80 galones. Perfecto para herramientas neumáticas.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Llave de impacto Dewalt DCF899',
                'numero_serie' => 'LLV-DWT-021-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 54,
                'costo_reemplazo' => 2800.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 150,
                'descripcion' => 'Llave de impacto inalámbrica de 20V con torque máximo de 1500 ft-lbs.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Taladro de columna JET JDP-20MF',
                'numero_serie' => 'TDC-JET-022-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 96,
                'costo_reemplazo' => 4200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 180,
                'descripcion' => 'Taladro de columna profesional de 20" con motor de 1 HP. Precisión para trabajos de taller.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Máquina de soldar MIG Miller Multimatic 215',
                'numero_serie' => 'SLM-MLR-023-2024',
                'categoria_id' => $categoriaMap['electronica'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 48,
                'costo_reemplazo' => 6200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 120,
                'descripcion' => 'Soldadora MIG multiproceso con control digital. Versátil para diferentes tipos de metal.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Compresor de tornillo Atlas Copco GA 11',
                'numero_serie' => 'CMT-ACP-024-2024',
                'categoria_id' => $categoriaMap['otra'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 120,
                'costo_reemplazo' => 18500.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 90,
                'descripcion' => 'Compresor de tornillo rotativo de 11 kW. Alta eficiencia energética para uso industrial.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Prensa hidráulica Enerpac RC-106',
                'numero_serie' => 'PRN-ENP-025-2024',
                'categoria_id' => $categoriaMap['construccion'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 72,
                'costo_reemplazo' => 8900.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 180,
                'descripcion' => 'Prensa hidráulica de 10 toneladas con capacidad de 6". Ideal para trabajos de reparación.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Pulidora orbital Festool RO 150',
                'numero_serie' => 'PLD-FST-026-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 66,
                'costo_reemplazo' => 3200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 120,
                'descripcion' => 'Pulidora orbital profesional con sistema de extracción de polvo. Acabados perfectos.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Lijadora de banda Bosch PBS 75 AE',
                'numero_serie' => 'LJD-BSH-027-2024',
                'categoria_id' => $categoriaMap['electrica'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 48,
                'costo_reemplazo' => 1900.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 90,
                'descripcion' => 'Lijadora de banda con velocidad variable. Excelente para desbaste y lijado de superficies.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Herramienta de torque digital CDI 1500FT-LB',
                'numero_serie' => 'TRQ-CDI-028-2024',
                'categoria_id' => $categoriaMap['medicion'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 36,
                'costo_reemplazo' => 1200.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 365,
                'descripcion' => 'Herramienta de torque digital con precisión de ±2%. Rango de 30-1500 ft-lbs.',
                'foto' => null,
                'tecnico_id' => null,
            ],
            [
                'nombre' => 'Detector de voltaje Klein Tools ET300',
                'numero_serie' => 'DTC-KLT-029-2024',
                'categoria_id' => $categoriaMap['medicion'] ?? null,
                'estado' => 'asignada',
                'vida_util_meses' => 24,
                'costo_reemplazo' => 180.00,
                'requiere_mantenimiento' => false,
                'dias_para_mantenimiento' => null,
                'descripcion' => 'Detector de voltaje digital con pantalla LCD. Detección de voltaje AC hasta 600V.',
                'foto' => null,
                'tecnico_id' => $tecnicos->isNotEmpty() ? $tecnicos->random()->id : null,
            ],
            [
                'nombre' => 'Herramienta de corte hidráulico Holmatro',
                'numero_serie' => 'CRTHYD-030-2024',
                'categoria_id' => $categoriaMap['construccion'] ?? null,
                'estado' => 'disponible',
                'vida_util_meses' => 48,
                'costo_reemplazo' => 4500.00,
                'requiere_mantenimiento' => true,
                'dias_para_mantenimiento' => 120,
                'descripcion' => 'Herramienta de corte hidráulico para rescate. Capacidad de corte hasta 2" de acero.',
                'foto' => null,
                'tecnico_id' => null,
            ]
        ];

        foreach ($herramientas as $herramienta) {
            Herramienta::create($herramienta);
        }
    }
}
