version: '3.8'

services:
  # Aplicación Laravel
  app:
    build: .
    container_name: cdd_app
    restart: unless-stopped
    working_dir: /var/www/cdd_app
    volumes:
      - ./:/var/www/cdd_app
      - /var/www/cdd_app/vendor
      - /var/www/cdd_app/node_modules
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=cdd_app_prod
      - DB_USERNAME=cdd_user
      - DB_PASSWORD=Contpaqi1.
    depends_on:
      - db
      - redis
    networks:
      - cdd_network

  # Base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: cdd_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: cdd_app_prod
      POSTGRES_USER: cdd_user
      POSTGRES_PASSWORD: Contpaqi1.
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./optimize_database.sql:/docker-entrypoint-initdb.d/01_optimize.sql
    ports:
      - "5432:5432"
    networks:
      - cdd_network

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: cdd_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cdd_network

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: cdd_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cdd_network

volumes:
  db_data:

networks:
  cdd_network:
    driver: bridge
