services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=production
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
    restart: unless-stopped

  queue:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=production
    command: php artisan queue:work --sleep=1 --tries=3
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  db_data:
  redis_data: